name: Validate YAML
on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      # - id: generate-mapping
      #   run: |
      #     mapping=$(jq -n '{}')
      #     for vdir in Fastbot/v*; do
      #       version=${vdir#Fastbot/}
      #       mapping=$(jq ".\"config/schema.json\" = [\"$version/**/*.{yaml,yml}\"]" <<< "$mapping")
      #     done
      #     echo "mapping=$(printf '%s' "$mapping" | jq -c .)" >> $GITHUB_OUTPUT

      - uses: InoUno/yaml-ls-check@develop
        with:
          root: Fastbot/
          schemaMapping: | 
            {
              "schema.json": [ "examples/*.{yaml,yml}" ]
            }